import { useMemo, useState } from 'react'
import { Link, NavLink, Route, Routes } from 'react-router-dom'
import { Wrench, Zap, Wind, Sparkles, Paintbrush, Hammer, MapPin, Phone, Star, ShieldCheck, Clock, CheckCircle2, Menu, X, MessageCircle, BadgePercent, Home as HomeIcon, Camera, PackageCheck } from 'lucide-react'
import './upgrade.css'

const contact = {
  brand: 'NorthStar Home Services',
  phone: '+1 (000) 000-0000',
  phoneHref: 'tel:+10000000000',
  whatsappHref: 'https://wa.me/10000000000?text=Hi%20NorthStar%20Home%20Services%2C%20I%20want%20a%20quote.',
  email: 'hello@mspixelpulse.com',
  location: 'Toronto, Ontario, Canada',
}

const categoryDetails = [
  { category: 'Plumbing', icon: Wrench, image: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=900&q=80', intro: 'Leak fixes, drain cleaning, fixture replacement, and small plumbing repairs for busy homeowners.', services: ['Leak repair','Drain cleaning','Toilet repair','Faucet replacement','Sink installation','Pipe inspection','Water pressure check','Shower valve repair','Garbage disposal help','Basement plumbing check'], regular: '$129', offer: '$79', package: 'Home Plumbing Check', response: 'Same-day demo' },
  { category: 'Electrical', icon: Zap, image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=900&q=80', intro: 'Outlet checks, lighting upgrades, switch replacement, and home safety support.', services: ['Outlet repair','Switch replacement','Light fixture install','Ceiling fan install','Breaker check','Smart thermostat wiring','Doorbell install','Smoke alarm replacement','Panel inspection request','Safety walkthrough'], regular: '$159', offer: '$99', package: 'Electrical Safety Visit', response: 'Fast quote' },
  { category: 'HVAC', icon: Wind, image: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=900&q=80', intro: 'Heating and cooling request flows for seasonal tune-ups, filter changes, and comfort checks.', services: ['Furnace service','AC tune-up','Filter replacement','Thermostat setup','Vent inspection','Heating check','Cooling check','Airflow review','Maintenance reminders','Seasonal service visit'], regular: '$189', offer: '$129', package: 'Seasonal HVAC Tune-Up', response: 'Seasonal support' },
  { category: 'Cleaning', icon: Sparkles, image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80', intro: 'Clear cleaning packages for homes, condos, apartments, offices, and move-out requests.', services: ['Standard cleaning','Deep cleaning','Move-out cleaning','Kitchen cleaning','Bathroom cleaning','Dusting','Floor cleaning','Post-renovation cleaning','Office cleaning','Short-term rental refresh'], regular: '$219', offer: '$149', package: 'Deep Clean Starter', response: 'Weekly or one-time' },
  { category: 'Painting', icon: Paintbrush, image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=900&q=80', intro: 'Room refreshes, touch-ups, trim painting, wall prep, and small interior painting jobs.', services: ['Interior painting','Accent wall','Trim painting','Door painting','Drywall patching','Paint touch-ups','Room refresh','Colour change','Baseboard repair','Small condo painting'], regular: '$349', offer: '$249', package: 'Room Refresh Offer', response: 'Room refresh' },
  { category: 'Roofing', icon: ShieldCheck, image: 'https://images.unsplash.com/photo-1632759145351-1d592919f522?auto=format&fit=crop&w=900&q=80', intro: 'Roof inspection requests, gutter cleaning, small shingle repairs, and leak check workflows.', services: ['Leak inspection','Shingle repair request','Gutter cleaning','Downspout check','Roof maintenance','Flashing check','Storm damage review','Attic leak review','Minor repair quote','Seasonal roof check'], regular: '$279', offer: '$199', package: 'Roof Check Visit', response: 'Inspection ready' },
  { category: 'Landscaping', icon: HomeIcon, image: 'https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=900&q=80', intro: 'Yard cleanup, lawn care, garden maintenance, snow removal placeholders, and seasonal work.', services: ['Lawn mowing','Yard cleanup','Garden maintenance','Leaf cleanup','Weed control request','Mulch refresh','Hedge trimming','Seasonal cleanup','Snow removal placeholder','Curb appeal package'], regular: '$119', offer: '$69', package: 'Curb Appeal Visit', response: 'Seasonal work' },
  { category: 'Handyman', icon: Hammer, image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=900&q=80', intro: 'Small repair jobs, installation help, assembly, doors, drywall, fixtures, and general maintenance.', services: ['Furniture assembly','Door repair','Drywall patch','Fixture install','Shelf mounting','TV mounting request','Caulking','Cabinet hardware','Small repairs','Rental unit fix list'], regular: '$139', offer: '$89', package: 'Handyman Starter Visit', response: 'Small jobs' },
  { category: 'Appliance Repair', icon: PackageCheck, image: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80', intro: 'Appliance service request pages for refrigerators, washers, dryers, ovens, and dishwashers.', services: ['Washer check','Dryer check','Dishwasher issue','Oven issue','Fridge check','Microwave request','Appliance install','Noise review','Leak review','Maintenance visit'], regular: '$169', offer: '$109', package: 'Appliance Check', response: 'Diagnostic demo' }
]

const services = categoryDetails.flatMap((cat, index) => cat.services.slice(0, 4).map((service, i) => ({ id: `${cat.category}-${i}`, title: service, category: cat.category, icon: cat.icon, price: i === 0 ? cat.offer : `From $${79 + (index * 10) + i * 20}`, response: cat.response, desc: `${service} request flow for ${cat.category.toLowerCase()} customers with clear quote CTA and mobile-first booking.`, tasks: cat.services.slice(i, i + 3).length === 3 ? cat.services.slice(i, i + 3) : cat.services.slice(0, 3) })))
const areas = ['Toronto','Brampton','Mississauga','Vaughan','Oakville','Milton','Hamilton','Markham','Richmond Hill','Scarborough','North York','Etobicoke','Burlington','Ajax','Pickering','Whitby']
const packages = [
  ['Essential Home Care','$49/mo','$69/mo','For small homes and condos',['Priority quote request','Seasonal reminder emails','One annual home check','Member-only offer pricing']],
  ['Family Home Plan','$89/mo','$119/mo','For active family homes',['Two home check visits','Plumbing/electrical priority','Cleaning discount placeholder','Weekend booking request']],
  ['Landlord Care Plan','$149/mo','$199/mo','For rentals and property managers',['Multi-unit service requests','Tenant-friendly quote flow','Repair checklist tracking','Move-out service bundle']],
  ['Annual Total Care','$999/yr','$1,299/yr','Best demo annual package',['Quarterly inspection visits','Service area priority','Discounted urgent request','Annual property care report']]
]
const gallery = [['Kitchen plumbing refresh','https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80'],['Clean living space','https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80'],['Electrical fixture work','https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=900&q=80'],['HVAC tune-up visit','https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=900&q=80'],['Fresh painted room','https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=900&q=80'],['Curb appeal cleanup','https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=900&q=80']]
const reviews = [['Demo Homeowner','Plumbing','The service list is easy to understand and I can request a quote in seconds.'],['Demo Landlord','Cleaning','The packages make this feel like a real monthly home care website.'],['Demo Property Manager','Electrical','The mobile call and WhatsApp actions are exactly what local service clients need.'],['Demo Family Customer','Painting','The offer pricing and before/after style visuals make the page more engaging.'],['Demo Condo Owner','Handyman','Everything feels simple, readable, and easy to access on my phone.'],['Demo Realtor','Move-Out Services','This layout would work well for property turnovers and rental repairs.']]
const faqs = [['Is NorthStar Home Services a real company?','No. This is a fictional demo website created by MSPixelPulseAgency.'],['Are these offers and prices real?','No. All offers, crossed-out prices, memberships, and package prices are demo placeholders only.'],['Can this website be customized for a real home service business?','Yes. Branding, services, pricing, cities, reviews, photos, and forms can be customized.'],['Can WhatsApp be connected?','Yes. The WhatsApp button can use a real business number in production.'],['Does the quote form work?','The demo includes frontend forms. In production they can connect to EmailJS, Formspree, CRM, Google Sheets, or a backend API.'],['Can this work for subscriptions?','Yes. The membership/package sections can connect to Stripe, booking software, or a CRM.'],['Is this mobile-friendly?','Yes. It includes sticky mobile actions, easy service access, and large tap targets.'],['Can this help local SEO?','Yes. It includes service categories, service area cards, FAQ content, and quote CTAs.']]

function Header(){ const [open,setOpen]=useState(false); const links=[['/','Home'],['/about','About'],['/services','Services'],['/areas','Areas'],['/pricing','Pricing'],['/reviews','Reviews'],['/faq','FAQ'],['/contact','Contact']]; return <header className="header"><a className="skip" href="#main">Skip to content</a><div className="topbar"><span>Limited demo offers live now</span><a href={contact.phoneHref}>Call {contact.phone}</a><a href={contact.whatsappHref} target="_blank" rel="noreferrer">WhatsApp Quote</a><Link to="/quote">Request Quote</Link></div><nav className="nav container" aria-label="Main navigation"><Link className="logo" to="/"><span>N</span><b>NorthStar<small>Home Services</small></b></Link><div className="desktop-nav">{links.map(([to,label])=><NavLink key={to} to={to}>{label}</NavLink>)}<Link className="btn primary pulse" to="/quote">Get Quote</Link></div><button className="menu" onClick={()=>setOpen(true)} aria-label="Open menu"><Menu size={26}/></button></nav>{open && <div className="mobile-menu"><button onClick={()=>setOpen(false)} className="close"><X/> Close</button>{links.map(([to,label])=><NavLink onClick={()=>setOpen(false)} key={to} to={to}>{label}</NavLink>)}<a onClick={()=>setOpen(false)} href={contact.whatsappHref} target="_blank" rel="noreferrer">WhatsApp Quote</a><Link onClick={()=>setOpen(false)} className="btn primary" to="/quote">Get Quote</Link></div>}</header> }
function SectionTitle({eyebrow,title,text}){return <div className="section-title reveal"><span>{eyebrow}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
function ServiceCard({service}){const Icon=service.icon;return <article className="card service-card reveal"><div className="card-top"><Icon className="service-icon"/><span className="offer-badge">Offer</span></div><p className="tag">{service.category}</p><h3>{service.title}</h3><p>{service.desc}</p><ul>{service.tasks.map(t=><li key={t}>{t}</li>)}</ul><div className="meta"><b>{service.price}</b><span>{service.response}</span></div><Link className="btn soft" to="/quote">Get Quote</Link></article>}
function ServiceFinder(){ const [query,setQuery]=useState(''); const [cat,setCat]=useState('All'); const cats=['All',...categoryDetails.map(c=>c.category)]; const filtered=useMemo(()=>services.filter(s=>(cat==='All'||s.category===cat) && [s.title,s.category,s.desc,...s.tasks].join(' ').toLowerCase().includes(query.toLowerCase())),[query,cat]); return <section className="section finder"><div className="container"><SectionTitle eyebrow="Quick service finder" title="Find the exact service you need" text="Search by service or tap a category. The demo filter works instantly on the page."/><div className="search-box glow"><label htmlFor="service-search">Search services</label><input id="service-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search drain cleaning, outlet repair, deep cleaning, painting..."/></div><div className="chips">{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><p className="result-count">{filtered.length} service result{filtered.length!==1?'s':''}</p><div className="grid cards-grid">{filtered.map(s=><ServiceCard key={s.id} service={s}/>)}</div>{(query||cat!=='All')&&<button className="btn soft" onClick={()=>{setQuery('');setCat('All')}}>Clear Filters</button>}</div></section> }
function QuoteForm(){return <form className="form" onSubmit={e=>e.preventDefault()}><div className="two"><label>Name<input required placeholder="Your name"/></label><label>Email<input type="email" required placeholder="you@example.com"/></label></div><div className="two"><label>Phone<input placeholder="+1 (000) 000-0000"/></label><label>City<input placeholder="Toronto"/></label></div><div className="two"><label>Service Category<select>{categoryDetails.map(c=><option key={c.category}>{c.category}</option>)}</select></label><label>Urgency<select><option>Today</option><option>This week</option><option>This month</option><option>Just researching</option></select></label></div><label>Interested Package<select><option>One-time quote</option>{packages.map(p=><option key={p[0]}>{p[0]}</option>)}</select></label><label>Message<textarea rows="5" placeholder="Tell us what you need help with..."></textarea></label><button className="btn primary" type="submit">Submit Quote Request</button><p className="fine">Demo form only. Connect to email, CRM, Google Sheets, booking software, or backend API in production.</p></form>}
function Home(){return <><section className="hero decorated"><div className="container hero-grid"><div><span className="eyebrow">Mobile-first local service demo</span><h1>Reliable home services with clear offers, packages, and fast quotes.</h1><p>Clean, accessible, and built for calls, WhatsApp messages, quote requests, service packages, subscriptions, reviews, and local service growth.</p><div className="actions"><Link className="btn primary pulse" to="/quote">Get Free Quote</Link><a className="btn whatsapp" href={contact.whatsappHref} target="_blank" rel="noreferrer"><MessageCircle size={18}/> WhatsApp</a><Link className="btn secondary" to="/services">View Services</Link></div></div><div className="hero-card float"><img src="https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80" alt="Home service professional cleaning a bright room"/><div className="trust"><span><Clock/> Same-Day Demo</span><span><BadgePercent/> Offer Prices</span><span><Star/> 4.9 Demo Rating</span></div></div></div></section><section className="section offer-strip"><div className="container offer-grid">{[['Plumbing Check','$129','$79'],['Deep Clean','$219','$149'],['HVAC Tune-Up','$189','$129'],['Handyman Visit','$139','$89']].map(([name,oldp,newp])=><div className="deal" key={name}><span>Limited demo offer</span><h3>{name}</h3><p><del>{oldp}</del> <b>{newp}</b></p><Link to="/quote">Claim Offer</Link></div>)}</div></section><ServiceFinder/><CategoryShowcase/><WorkGallery/><Packages/><Feedback/><WhatsAppSection/><section className="section alt"><div className="container"><SectionTitle eyebrow="How it works" title="A simple path from service need to booked visit"/><div className="steps">{['Choose your service','Tell us the issue','Compare offer/package','Book a time','Service gets completed'].map((s,i)=><div className="step reveal" key={s}><b>{i+1}</b><h3>{s}</h3><p>Clear, mobile-friendly step for local service customers.</p></div>)}</div></div></section><section className="section"><div className="container"><SectionTitle eyebrow="Service areas" title="Home services across GTA communities"/><div className="grid area-grid">{areas.slice(0,8).map(city=><Link className="area reveal" key={city} to="/areas"><h3>{city}</h3><p>Request plumbing, electrical, cleaning, HVAC, handyman, and repair service in {city}.</p></Link>)}</div></div></section><CTA/></>}
function CategoryShowcase(){return <section className="section"><div className="container"><SectionTitle eyebrow="Full service categories" title="Detailed service lists for every home category" text="Each category shows common tasks, offer pricing, images, package names, and quote CTAs."/><div className="category-stack">{categoryDetails.map(cat=>{const Icon=cat.icon; return <article className="category-panel reveal" key={cat.category}><img src={cat.image} alt={`${cat.category} home service work visual`}/><div><div className="category-head"><Icon/><span>{cat.category}</span></div><h3>{cat.package}</h3><p>{cat.intro}</p><div className="price-row"><del>{cat.regular}</del><strong>{cat.offer}</strong><small>{cat.response}</small></div><div className="service-list">{cat.services.map(s=><span key={s}>{s}</span>)}</div><div className="actions compact"><Link className="btn primary" to="/quote">Book {cat.category}</Link><a className="btn secondary" href={contact.whatsappHref} target="_blank" rel="noreferrer">WhatsApp</a></div></div></article>})}</div></div></section>}
function WorkGallery(){return <section className="section alt"><div className="container"><SectionTitle eyebrow="Work visuals" title="Show real work categories with clean picture sections" text="Use this layout later for real before/after photos, technician images, and completed project galleries."/><div className="gallery-grid">{gallery.map(([title,img])=><figure className="work-card reveal" key={title}><img src={img} alt={`${title} demo work visual`}/><figcaption><Camera size={17}/>{title}</figcaption></figure>)}</div></div></section>}
function Packages(){return <section className="section packages"><div className="container"><SectionTitle eyebrow="Packages and subscriptions" title="One-time services, monthly care plans, and annual home protection offers" text="Demo packages show how local service companies can sell recurring home-care subscriptions."/><div className="grid pricing">{packages.map(([name,offer,regular,best,items])=><article className="card package-card reveal" key={name}><span className="offer-badge">Save more</span><h3>{name}</h3><p className="price"><del>{regular}</del><br/><b>{offer}</b></p><p>{best}</p><ul>{items.map(i=><li key={i}>{i}</li>)}</ul><Link className="btn primary" to="/quote">Choose Plan</Link></article>)}</div><p className="notice">All package, subscription, and offer prices are demo placeholders. Real pricing depends on service type, property size, parts, labour, location, and availability.</p></div></section>}
function Feedback(){return <section className="section"><div className="container"><SectionTitle eyebrow="Customer feedback" title="Demo feedback that makes the website feel real and trustworthy"/><div className="grid review-grid">{reviews.map(([name,service,text])=><article className="card review-card reveal" key={name}><strong>5.0 ★</strong><p className="tag">{service}</p><p>“{text}”</p><h3>{name}</h3></article>)}</div></div></section>}
function WhatsAppSection(){return <section className="section whatsapp-section"><div className="container contact-banner"><div><span className="eyebrow">Fast contact</span><h2>Want a faster quote? Message on WhatsApp.</h2><p>Give homeowners easy contact options: phone, WhatsApp, email, quote form, and booking request. This is perfect for mobile visitors.</p></div><div className="contact-actions"><a className="btn whatsapp" href={contact.whatsappHref} target="_blank" rel="noreferrer"><MessageCircle/> Chat on WhatsApp</a><a className="btn secondary" href={contact.phoneHref}><Phone/> Call Now</a><Link className="btn primary" to="/quote">Request Quote</Link></div></div></section>}
function About(){return <Page title="About NorthStar Home Services" eyebrow="About"><p>NorthStar Home Services is a fictional MSPixelPulseAgency demo showing how a local service business can present services, service areas, pricing, subscriptions, reviews, visuals, and quote forms online.</p><CategoryShowcase/></Page>}
function Services(){return <><Page title="All home services with detailed category lists" eyebrow="Services" text="A flexible services structure for plumbing, electrical, HVAC, cleaning, painting, roofing, landscaping, handyman, appliance repair, moving help, and more."/><ServiceFinder/><CategoryShowcase/><WorkGallery/></>}
function Areas(){const [q,setQ]=useState(''); const filtered=areas.filter(a=>a.toLowerCase().includes(q.toLowerCase()));return <Page title="Home services across the GTA and nearby communities" eyebrow="Service Areas" text="Search city cards and request service by area."><div className="search-box full"><label htmlFor="city-search">Search your city</label><input id="city-search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search your city"/></div><div className="grid area-grid">{filtered.map(city=><article className="area reveal" key={city}><h3>{city}</h3><p>Common demo services: plumbing, electrical, HVAC, cleaning, painting, roofing, landscaping, appliance repair, moving help, and handyman.</p><Link className="btn soft" to="/quote">Request Service in {city}</Link></article>)}</div></Page>}
function Pricing(){return <><Page title="Offers, packages, and subscriptions" eyebrow="Pricing" text="Real prices depend on the actual business, service, property, parts, labour, and availability."/><Packages/></>}
function Reviews(){return <><Page title="Demo reviews and customer feedback" eyebrow="Reviews"/><Feedback/></>}
function FAQ(){return <Page title="Common questions about this home services demo" eyebrow="FAQ"><div className="faq">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></Page>}
function Contact(){return <Page title="Contact NorthStar Home Services" eyebrow="Contact"><div className="contact-grid"><div className="grid"><div className="mini"><Phone/> {contact.phone}</div><div className="mini"><MessageCircle/> WhatsApp quote available</div><div className="mini">✉️ {contact.email}</div><div className="mini"><MapPin/> {contact.location}</div><div className="mini">Demo business hours</div></div><QuoteForm/></div><WhatsAppSection/></Page>}
function Quote(){return <Page title="Tell us what home service you need" eyebrow="Request Quote" text="A mobile-friendly quote form structure for one-time services, offer pricing, and home-care subscription plans."><div className="contact-grid"><div><div className="notice">This demo form can be connected to email, CRM, Google Sheets, booking software, or a backend API.</div><img className="side-img" src="https://images.unsplash.com/photo-1600573472592-401b489a3cdc?auto=format&fit=crop&w=900&q=80" alt="Clean home interior after home service"/></div><QuoteForm/></div></Page>}
function Page({eyebrow,title,text,children}){return <section className="section page"><div className="container"><SectionTitle eyebrow={eyebrow} title={title} text={text}/>{children}</div></section>}
function CTA(){return <section className="cta"><div className="container cta-inner"><h2>Need a home service website that gets calls, WhatsApp messages, quotes, and subscriptions?</h2><div><Link className="btn primary" to="/quote">Get Quote</Link><a className="btn secondary" href={contact.phoneHref}>Call Now</a></div></div></section>}
function Footer(){return <footer className="footer"><div className="container footer-grid"><div><h3>NorthStar Home Services</h3><p>A fictional MSPixelPulseAgency home services demo for local Canadian service businesses.</p><p className="fine">Services, prices, offers, subscriptions, reviews, and business details are demo placeholders only.</p></div><div><h4>Quick Links</h4><Link to="/services">Services</Link><Link to="/areas">Service Areas</Link><Link to="/pricing">Packages</Link><Link to="/quote">Request Quote</Link></div><div><h4>Contact</h4><p>{contact.location}</p><p>{contact.phone}</p><p>{contact.email}</p><a href={contact.whatsappHref} target="_blank" rel="noreferrer">WhatsApp demo quote</a></div></div></footer>}
function BottomBar(){return <div className="bottom-bar"><a href={contact.phoneHref}>Call</a><a href={contact.whatsappHref} target="_blank" rel="noreferrer">WhatsApp</a><Link to="/services">Services</Link><Link to="/quote">Quote</Link></div>}
export default function App(){return <><Header/><main id="main"><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/services" element={<Services/>}/><Route path="/areas" element={<Areas/>}/><Route path="/pricing" element={<Pricing/>}/><Route path="/reviews" element={<Reviews/>}/><Route path="/faq" element={<FAQ/>}/><Route path="/contact" element={<Contact/>}/><Route path="/quote" element={<Quote/>}/></Routes></main><Footer/><BottomBar/></>}